CUDNN_BENCHMARK: True
SEED: 29780131
MODEL:
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_resnet_backbone"
  # WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  WEIGHTS: "./output/ss/coco/model_final.pth" #64999
  # WEIGHTS: "./output/ps/model_final_94dc52.pkl" #64999
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  RESNETS:
    DEPTH: 50
    STEM_TYPE: "basic"  # not used
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    # NORM: "SyncBN"
    RES5_MULTI_GRID: [1, 1, 1]  # not used
DATASETS:
  TRAIN: ("coco_2017_train_panoptic_with_sem_seg",)
  TEST: ("coco_2017_val_panoptic_with_sem_seg",)  # to evaluate instance and semantic performance as well
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.0001
  #STEPS: (20000, 70000,120000)
  # STEPS: (15556, 70184)
  STEPS: (327778, 355092)
  MAX_ITER: 368750
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
INPUT:
  IMAGE_SIZE: 1024
  MIN_SCALE: 0.1
  MAX_SCALE: 2.0
  FORMAT: "RGB"
  DATASET_MAPPER_NAME:  "coco_panoptic_lsj"  #"coco_unified_lsj"
  # MAX_SIZE_TEST: 1024
  # MIN_SIZE_TEST: 736
TEST:
  EVAL_PERIOD: 5000
  DETECTIONS_PER_IMAGE: 100
  # AUG:
  #   ENABLED: True    
  #   MIN_SIZES: [512, 768, 1024, 1280, 1536, 1792]
  #   MAX_SIZE: 4096
  #   FLIP: True

DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 6
VERSION: 2
#python ./train_net.py --config-file configs/coco/panoptic-segmentation/maskformer2_R50_bs16_50ep.yaml --machine-rank 0 --num-machines 2 --num-gpus 2 --dist-url 'tcp://127.0.0.1:50152'